version: '3.8'
services:
  spotify-app:
    build: .
    container_name: spotify-pwa
    ports:
      - "8060:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      # CasaOS Web UI Labels
      - "casaos.enable=true"
      - "casaos.name=Spotify PWA"
      - "casaos.description=Vue.js Spotify Clone - Music Streaming PWA"
      - "casaos.icon=https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/spotify.svg"
      - "casaos.category=Entertainment"
      - "casaos.port=8060"
      - "casaos.web_ui=http://192.168.1.8:8060"
      - "casaos.scheme=http"
      - "casaos.host=192.168.1.8"
      # Additional metadata
      - "org.opencontainers.image.title=Spotify PWA"
      - "org.opencontainers.image.description=Beautiful Music Streaming App built with Vue.js"
      - "org.opencontainers.image.url=http://192.168.1.8:8060"
    networks:
      - casaos
    volumes:
      # Optional: Mount for logs if needed
      - ./logs:/var/log/nginx:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  casaos:
    external: true
    name: casaos